include(${CMAKE_CURRENT_LIST_DIR}/add_cache_flag.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/check_san_option.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/print.cmake)

check_san_option("ASAN")
set(ASAN ${SAN_OPTION})
check_san_option("LSAN")
set(LSAN ${SAN_OPTION})
check_san_option("MSAN")
set(MSAN ${SAN_OPTION})
check_san_option("TSAN")
set(TSAN ${SAN_OPTION})
check_san_option("UBSAN")
set(UBSAN ${SAN_OPTION})

message(STATUS "sqlite: SAN=${LSAN}")

if(ASAN)
  print("Address Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/sanitize_address.cmake)
elseif(LSAN)
  print("Leak Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/sanitize_leak.cmake)
elseif(MSAN)
  print("Memory Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/sanitize_memory.cmake)
elseif(TSAN)
  print("Thread Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/sanitize_thread.cmake)
elseif(UBSAN)
  print("Undefined Behavior Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/sanitize_undefined.cmake)
endif()
