include(${CMAKE_CURRENT_LIST_DIR}/utils.cmake)

if(SAN)
  if (DEFINED POLLY_FLAGS_SANITIZE_ADDRESS_CMAKE_)
    return()
  else ()
    set(POLLY_FLAGS_SANITIZE_ADDRESS_CMAKE_ 1)
  endif ()

  set(SAN_FLAGS -g)
  if(SAN STREQUAL "ASAN")
    print("Address Sanitizer is enabled")
    include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/sanitize_address.cmake)
  elseif(SAN STREQUAL "LSAN")
    print("Leak Sanitizer is enabled")
    include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/sanitize_leak.cmake)
  elseif(SAN STREQUAL "MSAN")
    print("Memory Sanitizer is enabled")
    include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/sanitize_memory.cmake)
  elseif(SAN STREQUAL "TSAN")
    print("Thread Sanitizer is enabled")
    include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/sanitize_thread.cmake)
  elseif(SAN STREQUAL "UBSAN")
    print("Undefined Behavior Sanitizer is enabled")
    include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/sanitize_undefined.cmake)
  endif()
  process_sanitizer_flags()
endif()