function(print)
  message(STATUS "[${CMAKE_PROJECT_NAME}] ${ARGV}")
endfunction()

function(fatal_error)
  message(FATAL_ERROOR "[${CMAKE_PROJECT_NAME}] ${ARGV}")
endfunction()

function(add_cache_flag var_name flag)
  set(spaced_string " ${${var_name}} ")
  string(FIND "${spaced_string}" " ${flag} " flag_index)
  if(NOT flag_index EQUAL -1)
    return()
  endif()
  string(COMPARE EQUAL "" "${${var_name}}" is_empty)
  if(is_empty)
    # beautify: avoid extra space at the end if var_name is empty
    set("${var_name}" "${flag}" CACHE STRING "" FORCE)
  else()
    set("${var_name}" "${flag} ${${var_name}}" CACHE STRING "" FORCE)
  endif()
endfunction()

function (process_sanitizer_flags)
    foreach(FLAG IN LISTS SAN_FLAGS)
        add_cache_flag(CMAKE_CXX_FLAGS ${FLAG})
        add_cache_flag(CMAKE_C_FLAGS ${FLAG})
        add_cache_flag(CMAKE_EXE_LINKER_FLAGS ${FLAG})
        add_cache_flag(CMAKE_SHARED_LINKER_FLAGS ${FLAG})
    endforeach()
endfunction()